{
  "Comment": "Fail state machine, showing how to use the fail step. Note that any error in tasks will fail the execution by default, this is just to make it explicit (for example, catch the exception, do some cleanup than fail)",
  "StartAt": "Fail",
  "States": {
    "Fail": {
      "Type": "Fail",
      "Error": "ExampleError",
      "Cause": "Error caused by a step function definition that always fails",
      "Comment": "Example of the fail state, note that this is not the best way to use it as it does nothing but failing"
    }
  }
}